# Generated by Django 3.0.3 on 2020-02-18 11:06

import answersheet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=answersheet.models.AnswerSheet.getImagePath)),
                ('marks', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
