# Generated by Django 3.0.3 on 2020-02-19 05:38

import answersheet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answersheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=answersheet.models.AnswerSheet.getImagePath),
        ),
    ]
