# Generated by Django 3.0.3 on 2020-02-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answersheet', '0005_auto_20200219_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_login_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_from_test_login', models.CharField(max_length=100)),
                ('password_from_test_login', models.CharField(max_length=100)),
            ],
        ),
    ]
