# Generated by Django 3.0.3 on 2020-02-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answersheet', '0006_test_login_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='summ',
            field=models.TextField(blank=True, null=True),
        ),
    ]
